version: "3.8"

services:
  app:
    build: .
    container_name: replay-ocr-app
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - RATE_LIMITS=${RATE_LIMITS}
    volumes:
      - .:/app
      - ./src/.env:/app/src/.env # Mount the .env file for local development
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
